sudo: false
language: node_js
node_js:
  - 14.15.4
cache: npm
branches:
  only:
    - master # build master branch only
install:
  - npm install
script:
  - hexo generate # generate static files
  - cp CNAME public/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
