################################################################# 网站信息>>> #################################################################
title: xiaobu-home
subtitle: 技术文章,资源分享
description: 小布cvg,小布,张桓个人博客,分享技术文章,福利资源,心得体会,个人笔记...
keywords:
  - 猿对视
  - 技术文章
  - 福利资源
  - 个人博客
  - 小布cvg
  - 小布
  - 张桓
  - 心得分享
  - 搬运整理
author: 张桓
language: zh-CN
timezone: Asia/Shanghai


################################################################# 网址信息>>> #################################################################
url: https://home.xiaobu.site
# 永久链接格式
permalink: archives/:abbrlink.html
# 永久链接各部分默认值
permalink_defaults: null
# 改写 permalink 的值来美化 URL
pretty_urls:
  trailing_index: true
  trailing_html: true


################################################################# 目录信息>>> #################################################################
# 资源文件夹，这个文件夹用来存放内容
source_dir: source
# 公共文件夹，这个文件夹用于存放生成的站点文件
public_dir: public
# 标签文件夹
tag_dir: tags
# 归档文件夹
archive_dir: archives
# 分类文件夹
category_dir: categories
# Include code 文件夹，source_dir 下的子目录
code_dir: downloads/code
# 国际化（i18n）文件夹
i18n_dir: ':lang'
# 跳过指定文件的渲染。匹配到的文件将会被不做改动地复制到 public 目录中。您可使用 glob 表达式来匹配路径
skip_render: null


################################################################# 文章信息>>> #################################################################
# 新文章的文件名称
new_post_name: ':title.md'
# 预设布局
default_layout: post
# 把标题转换为 title case
titlecase: false
external_link:
  # 在新标签中打开链接
  enable: true
  # 对整个网站（site）生效或仅对文章（post）生效
  field: site
  # 需要排除的域名。主域名和子域名如 www 需分别配置
  exclude: ''
# 把文件名称转换为 (1) 小写或 (2) 大写
filename_case: 0
# 显示草稿
render_drafts: false
# 启动 Asset 文件夹
post_asset_folder: false
# relative_link
relative_link: false
# 显示未来的文章
future: true
# 代码块
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
# 代码块
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''


################################################################# 分类标签>>> #################################################################
# 默认分类
default_category: uncategorized
# 分类别名
category_map: null
# 标签别名
tag_map: null


################################################################# 时间日期>>> #################################################################
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: mtime


################################################################# 分页信息>>> #################################################################
per_page: 10
pagination_dir: page


################################################################# 扩展信息>>> #################################################################
theme: icarus
deploy: null
meta_generator: true


################################################################# 包不包括>>> #################################################################
# Hexo 默认会不包括 source/ 下的文件和文件夹（包括名称以下划线和 . 开头的文件和文件夹，Hexo 的 _posts 和 _data 等目录除外）。
# 通过设置此字段将使 Hexo 处理他们并将它们复制到 source 目录下。
include: null
# Hexo 不包括 source/ 下的这些文件和目录
exclude: null
# Hexo 会忽略整个 Hexo 项目下的这些文件夹或文件
ignore: null


################################################################# 插件配置>>> #################################################################
Plugins:
  - hexo-generator-baidu-sitemap
  - hexo-generator-sitemap
  - hexo-generator-feed
baidusitemap:
  path: baidusitemap.xml
sitemap:
  path: sitemap.xml
feed:
  type: atom
  path: atom.xml
  limit: 20
abbrlink:
  alg: crc32  # 算法：crc16(default) and crc32
  rep: hex    # 进制：dec(default) and hex

