# 导航栏
menu:
  home: /
  archives: /archives
  about: /about
  search: /search

# 个人简介
author: 张桓
authorimg: https://store.xiaobu.site/store-blog/avatar.jpg
blogname: 猿对视
notice: <p>程序员看事物的方式</p><p>404 Not Found</p>

# 社交
social:
  - name: Github
    icon_url: https://store.xiaobu.site/store-blog/github.png
    href: https://github.com/xiaobucvg
  - name: 掘金
    icon_url: https://store.xiaobu.site/store-blog/juejin.png
    href: https://juejin.cn/user/70018878936135
  - name: 知乎
    icon_url: https://store.xiaobu.site/store-blog/zhihu.png
    href: https://www.zhihu.com/people/aaaa-gui-gui
  - name: CSDN
    icon_url: https://store.xiaobu.site/store-blog/csdn.png
    href: https://blog.csdn.net/weixin_38844199
  - name: email
    icon_url: https://store.xiaobu.site/store-blog/Gmail.png
    href: www.1714005186@gmail.com
  - name: 微信
    icon_url: https://store.xiaobu.site/store-blog/weixin.png
    href:
  - name: QQ
    icon_url: https://store.xiaobu.site/store-blog/QQ.png
    href:
  - name: 微博
    icon_url: https://store.xiaobu.site/store-blog/weibo.png
    href: https://weibo.com/u/6067755914
  - name: 简书
    icon_url: https://store.xiaobu.site/store-blog/jianshu.png
    href: https://www.jianshu.com/u/1a1d86b8b698

# 网站icon图标
favicon: https://store.xiaobu.site/store-blog/favicon.ico

# 首页/文章是否显示分类标签
show_post_category: true
show_post_tags: true

# 侧边栏
sidebar: true
widgets:
  - notice
  - category
  - tag
  - recent_posts
  - archive
  - links

# 友情链接
links:
  - title: 求索日记
    url: https://www.shuxhan.com

# 建站时间
buildtime: 2022
datetime: 01/27/2022 00:00:00  # 本站已安全运行时间

# 代码复制
codeblock:
  copy_button:
    enable: true
    result: true
  copyright:
    enable: true
    content: \n/**\n* 感谢您复制代码，使用代码请注明引用出处\n* zhanghuan @ https://blog.xiaobu.site\n*/

# 百度分析
baidu_analytics: aecc9e08d716b19081eaf6963e648f46
# 谷歌分析
google_analytics:

