################################### 配置主题> ###################################
# 首页博客名称
logo_title: 小布CVG

# 默认主题风格 black or white
style: white

# 主题 ico
favicon: /favicon.ico

# 主题菜单
# 需要新建页面：hexo new page "页面地址"
menu:
  文章: /project
  友情链接: /links
  关于: /about
  Github: https://github.com/xiaobucvg

# valine 评论 , 使用说明见 https://valine.js.org
# 做了域名限制，请改成自己的 KEY
# 如不使用valine功能，将enable设为false即可
valine:
  enable: true
  appId: Xzvozzq9Js3RB8cdgGFP7RP6-gzGzoHsz
  appKey: U47lrRiTDWUlYtJeL0NytIrc

################################### <配置主题 ###################################